/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VAIO
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        setVisible(true);
        setSize(800,800);
        example.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        example = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jButton1.setText("LET'S MAKE YOUR PACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 40, 220, 50);

        jButton2.setText("BASIC PACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(70, 130, 230, 50);

        jButton3.setText("SILVER PACK");
        jPanel1.add(jButton3);
        jButton3.setBounds(70, 230, 230, 50);

        jTabbedPane1.addTab("HOME", jPanel1);

        jPanel2.setLayout(null);

        jLabel1.setText("TRAI RULES SIMPLIFIED");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(230, 20, 250, 14);

        jLabel2.setText("ACCORDING TO TRAI,THERE ARE MORE THAN 500 AND 300 FREE TO AIR AND PAID CHANNELS RESPECTIVELY.");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 70, 700, 30);

        jLabel3.setText("SUBSCRIBER CAN SELECT BASED ON PREFERENCES(IN FORM OF A' LA CARTE AND BOUQUET).");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 110, 650, 30);

        jLabel4.setText("SUBSCRIBERS ARE REQURED TO PAY A NETWORK CAPACITY FEE(NCF=130+18% GST=rs153.4) TO MAKRE A BASIC PACK(100 CHANNELS).");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 170, 810, 20);

        jLabel5.setText("OUT OF HUNDRED CHANNELS 25 CHANNELS ARE DD NATIONAL(MADATORY).");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 220, 670, 20);

        jLabel6.setText("REAMAINING 75 CAN BE FTA OR PAID, WHICH SUBSCRIBER HAVE TO SELECT.");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 260, 650, 20);

        jLabel7.setText("EXTRA FEE OF rs 20 IS CHARGED IF CHANNELS EXCEEDS 100 FOR PER SLAB OF 25 CHANNELS.");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 300, 630, 30);

        jLabel8.setText("*");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 80, 20, 14);

        jLabel9.setText("*");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 120, 10, 20);

        jLabel10.setText("*");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 174, 10, 20);

        jLabel11.setText("*");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 220, 20, 20);

        jLabel12.setText("*");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 270, 20, 14);

        jLabel13.setText("*");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 310, 20, 20);

        jButton4.setText("CHECK EXAMPLE ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(30, 350, 190, 40);

        example.setColumns(20);
        example.setRows(5);
        example.setText("CONSIDER I MAKING A PACK OF 100 CHANNELS CONSISTING OF THE FOLLOWING:-\n\n* FREE TO AIR(25 CHANNELS)(PRICE = rs 0.00)\n   LIKE: R.BHARAT\n\n* PAID(25 CHANNELS)(PRICE = rs 135)\n   LIKE: A'LA CARTE BASED: STARSPORTS\n         BOUQUET BASED: SONY HAPPY INDIA PACK\n\n* TOTAL CHANNELS IN MY PACK=25+25+25*=75\n   (* = DD NATIONAL CHANNELS PRE PROVIDED)\n\n* PRICE = 130+0+135+47.7(18% GST)= rs 312.7  ");
        jScrollPane1.setViewportView(example);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(290, 340, 520, 180);

        jTabbedPane1.addTab("HELP", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 840, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       home1 h=new home1(); //
       h.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       example.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea example;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
