
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VAIO
 */
public class homea extends javax.swing.JFrame {

    private Object rb1;

      ArrayList <String> sdc=new ArrayList<>();
       ArrayList <Integer> sdp=new ArrayList<>();
        ArrayList <String> hdc=new ArrayList<>();
         ArrayList <Integer> hdp=new ArrayList<>();

    /**
     * Creates new form home
     */
    public homea() {
       initComponents();
        setVisible(true);
        setSize(800,800);
        example.setVisible(false);
       // basic.addItem("25 channel DD National");
     //   basic.addItem("30 Free to air channel ");
        //basic.addItem("STAR BENGALI PACK");
        
       //// silver.addItem("25 channel DD National");
           //  silver.addItem("30 Free to air channel");
      //  silver.addItem("STAR BENGALI PACK");
      //  silver.addItem("SONNY HAPPY INDIA PACK");
      //  silver.addItem("COLORS PACK");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        home = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        example = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        cb2 = new javax.swing.JCheckBox();
        cb1 = new javax.swing.JCheckBox();
        ch = new javax.swing.JLabel();
        pk = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bs = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jCheckBox9 = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jCheckBox12 = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        jCheckBox13 = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        jCheckBox14 = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jLabel27 = new javax.swing.JLabel();
        jCheckBox20 = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        jCheckBox21 = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        jCheckBox22 = new javax.swing.JCheckBox();
        jLabel30 = new javax.swing.JLabel();
        jCheckBox23 = new javax.swing.JCheckBox();
        jLabel31 = new javax.swing.JLabel();
        jCheckBox24 = new javax.swing.JCheckBox();
        jLabel77 = new javax.swing.JLabel();
        jCheckBox25 = new javax.swing.JCheckBox();
        jLabel78 = new javax.swing.JLabel();
        jCheckBox26 = new javax.swing.JCheckBox();
        jLabel79 = new javax.swing.JLabel();
        jCheckBox27 = new javax.swing.JCheckBox();
        jLabel81 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jCheckBox28 = new javax.swing.JCheckBox();
        jLabel84 = new javax.swing.JLabel();
        jCheckBox29 = new javax.swing.JCheckBox();
        jLabel85 = new javax.swing.JLabel();
        jCheckBox30 = new javax.swing.JCheckBox();
        jLabel86 = new javax.swing.JLabel();
        jCheckBox31 = new javax.swing.JCheckBox();
        jLabel87 = new javax.swing.JLabel();
        jCheckBox32 = new javax.swing.JCheckBox();
        jLabel88 = new javax.swing.JLabel();
        jCheckBox80 = new javax.swing.JCheckBox();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jButton6 = new javax.swing.JButton();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        s1 = new javax.swing.JCheckBox();
        jPanel12 = new javax.swing.JPanel();
        starbt = new javax.swing.JButton();
        colorsbt = new javax.swing.JButton();
        sonybt = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        star = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        colors = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        sony = new javax.swing.JTextArea();
        srb1 = new javax.swing.JRadioButton();
        srb2 = new javax.swing.JRadioButton();
        srb3 = new javax.swing.JRadioButton();
        jLabel98 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabel1.setText("TRAI RULES SIMPLIFIED");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(230, 20, 250, 14);

        jLabel2.setText("ACCORDING TO TRAI,THERE ARE MORE THAN 500 AND 300 FREE TO AIR AND PAID CHANNELS RESPECTIVELY.");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 70, 700, 30);

        jLabel3.setText("SUBSCRIBER CAN SELECT BASED ON PREFERENCES(IN FORM OF A' LA CARTE AND BOUQUET).");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 110, 650, 30);

        jLabel4.setText("SUBSCRIBERS ARE REQURED TO PAY A NETWORK CAPACITY FEE(NCF=130+18% GST=rs153.4) TO MAKRE A BASIC PACK(100 CHANNELS).");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 170, 810, 20);

        jLabel5.setText("OUT OF HUNDRED CHANNELS 25 CHANNELS ARE DD NATIONAL(MADATORY).");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 220, 670, 20);

        jLabel6.setText("REAMAINING 75 CAN BE FTA OR PAID, WHICH SUBSCRIBER HAVE TO SELECT.");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 260, 650, 20);

        jLabel7.setText("EXTRA FEE OF rs 20 IS CHARGED IF CHANNELS EXCEEDS 100 FOR PER SLAB OF 25 CHANNELS.");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 300, 630, 30);

        jLabel8.setText("*");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 80, 20, 14);

        jLabel9.setText("*");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 120, 10, 20);

        jLabel10.setText("*");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 174, 10, 20);

        jLabel11.setText("*");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 220, 20, 20);

        jLabel12.setText("*");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 270, 20, 14);

        jLabel13.setText("*");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 310, 20, 20);

        jButton4.setText("CHECK EXAMPLE ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(30, 350, 190, 40);

        example.setColumns(20);
        example.setRows(5);
        example.setText("CONSIDER I MAKING A PACK OF 100 CHANNELS CONSISTING OF THE FOLLOWING:-\n\n* FREE TO AIR(25 CHANNELS)(PRICE = rs 0.00)\n   LIKE: R.BHARAT\n\n* PAID(25 CHANNELS)(PRICE = rs 135)\n   LIKE: A'LA CARTE BASED: STARSPORTS\n         BOUQUET BASED: SONY HAPPY INDIA PACK\n\n* TOTAL CHANNELS IN MY PACK=25+25+25*=75\n   (* = DD NATIONAL CHANNELS PRE PROVIDED)\n\n* PRICE = 130+0+135+47.7(18% GST)= rs 312.7  ");
        jScrollPane1.setViewportView(example);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(290, 340, 520, 180);

        home.addTab("HELP", jPanel2);

        jPanel1.setLayout(null);

        cb2.setText("RS.283.90");
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });
        jPanel1.add(cb2);
        cb2.setBounds(460, 270, 190, 50);

        cb1.setText("RS.211.80");
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        jPanel1.add(cb1);
        cb1.setBounds(460, 170, 190, 50);

        ch.setText("CH");
        jPanel1.add(ch);
        ch.setBounds(330, 380, 150, 30);

        pk.setText("PK");
        jPanel1.add(pk);
        pk.setBounds(330, 470, 160, 30);
        if(cb1.isSelected()==true)
        {
            pk.setText("basic");
        }
        else
        {
            pk.setText("silver");
        }

        jLabel16.setText("AMOUNT      =");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(590, 470, 90, 50);

        amount.setText("AMOUNT");
        jPanel1.add(amount);
        amount.setBounds(700, 490, 120, 20);
        jPanel1.add(jPanel4);
        jPanel4.setBounds(120, -40, 10, 10);
        jPanel1.add(jPanel5);
        jPanel5.setBounds(130, -40, 10, 10);

        jButton2.setText("BASIC PACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(170, 170, 230, 50);

        jButton3.setText("SILVER PACK");
        jPanel1.add(jButton3);
        jButton3.setBounds(170, 260, 230, 50);
        jPanel1.add(bs);
        bs.setBounds(330, 420, 400, 30);

        jLabel95.setText("BOUQUET SELECTED      =");
        jPanel1.add(jLabel95);
        jLabel95.setBounds(170, 420, 140, 30);

        jLabel96.setText("PACK SELECTED             =");
        jPanel1.add(jLabel96);
        jLabel96.setBounds(170, 470, 130, 30);

        jLabel97.setText("A' LA CARTE                    =");
        jPanel1.add(jLabel97);
        jLabel97.setBounds(170, 380, 130, 30);

        home.addTab("HOME", jPanel1);

        jPanel6.setLayout(null);

        jPanel3.setLayout(null);

        jPanel10.setLayout(null);

        jCheckBox3.setText("22. ZEE TV HD   -       RS");
        jPanel10.add(jCheckBox3);
        jCheckBox3.setBounds(410, 410, 150, 30);

        jCheckBox4.setText("2. ANIMAL PLANET HD-  RS");
        jPanel10.add(jCheckBox4);
        jCheckBox4.setBounds(10, 70, 160, 20);

        jLabel17.setText("4.60");
        jPanel10.add(jLabel17);
        jLabel17.setBounds(210, 70, 30, 20);

        jCheckBox5.setText("11. FOX HD             RS");
        jPanel10.add(jCheckBox5);
        jCheckBox5.setBounds(10, 420, 160, 20);

        jLabel18.setText("2.60");
        jPanel10.add(jLabel18);
        jLabel18.setBounds(210, 420, 22, 14);

        jCheckBox6.setText("3. BABY TV HD -               RS");
        jPanel10.add(jCheckBox6);
        jCheckBox6.setBounds(10, 110, 160, 20);

        jLabel19.setText("2.60");
        jPanel10.add(jLabel19);
        jLabel19.setBounds(210, 110, 22, 14);

        jCheckBox9.setText("4.  AXN HD-                   RS");
        jPanel10.add(jCheckBox9);
        jCheckBox9.setBounds(10, 140, 160, 30);

        jLabel20.setText("5.80");
        jPanel10.add(jLabel20);
        jLabel20.setBounds(210, 150, 22, 14);

        jPanel11.setLayout(null);

        jCheckBox10.setText("1. AAJ TAK HD   -       RS");
        jPanel11.add(jCheckBox10);
        jCheckBox10.setBounds(10, 20, 150, 30);

        jCheckBox11.setText("2. ANIMAL PLANET-  RS");
        jPanel11.add(jCheckBox11);
        jCheckBox11.setBounds(10, 70, 160, 20);

        jLabel21.setText("4.60");
        jPanel11.add(jLabel21);
        jLabel21.setBounds(210, 70, 30, 20);

        jLabel22.setText("3.60");
        jPanel11.add(jLabel22);
        jLabel22.setBounds(210, 30, 30, 20);

        jCheckBox12.setText("5. COLORS HD             RS");
        jPanel11.add(jCheckBox12);
        jCheckBox12.setBounds(10, 250, 160, 23);

        jLabel23.setText("9.60");
        jPanel11.add(jLabel23);
        jLabel23.setBounds(210, 200, 22, 14);

        jCheckBox13.setText("3. BABY TV-               RS");
        jPanel11.add(jCheckBox13);
        jCheckBox13.setBounds(10, 110, 160, 23);

        jLabel24.setText("2.60");
        jPanel11.add(jLabel24);
        jLabel24.setBounds(210, 110, 22, 14);

        jCheckBox14.setText("4.  AXN-                      RS");
        jPanel11.add(jCheckBox14);
        jCheckBox14.setBounds(10, 150, 160, 30);

        jLabel25.setText("5.80");
        jPanel11.add(jLabel25);
        jLabel25.setBounds(210, 150, 22, 14);

        jCheckBox15.setText("5. C N-                       RS");
        jPanel11.add(jCheckBox15);
        jCheckBox15.setBounds(10, 200, 160, 23);

        jCheckBox16.setText("5. C N-                       RS");
        jPanel11.add(jCheckBox16);
        jCheckBox16.setBounds(10, 200, 160, 23);

        jPanel10.add(jPanel11);
        jPanel11.setBounds(0, 0, 0, 0);

        jCheckBox17.setText("5. COLORS HD             RS");
        jPanel10.add(jCheckBox17);
        jCheckBox17.setBounds(10, 190, 160, 23);

        jLabel26.setText("19.80");
        jPanel10.add(jLabel26);
        jLabel26.setBounds(210, 190, 28, 14);

        jCheckBox18.setText("7 . TUNER HD             RS");
        jPanel10.add(jCheckBox18);
        jCheckBox18.setBounds(10, 260, 160, 20);

        jCheckBox19.setText("9. LIVING FOOD  HD             RS");
        jPanel10.add(jCheckBox19);
        jCheckBox19.setBounds(10, 330, 160, 20);

        jLabel27.setText("11.60");
        jPanel10.add(jLabel27);
        jLabel27.setBounds(210, 330, 28, 14);

        jCheckBox20.setText("10. DISNEY HD             RS");
        jPanel10.add(jCheckBox20);
        jCheckBox20.setBounds(10, 380, 160, 20);

        jLabel28.setText("13.60");
        jPanel10.add(jLabel28);
        jLabel28.setBounds(210, 380, 28, 14);

        jCheckBox21.setText("8. DISCOVERY HD             RS");
        jPanel10.add(jCheckBox21);
        jCheckBox21.setBounds(10, 290, 160, 20);

        jLabel29.setText("3.20");
        jPanel10.add(jLabel29);
        jLabel29.setBounds(210, 260, 22, 14);

        jCheckBox22.setText("1. AAJ TAK HD   -       RS");
        jPanel10.add(jCheckBox22);
        jCheckBox22.setBounds(10, 30, 150, 30);

        jLabel30.setText("3.60");
        jPanel10.add(jLabel30);
        jLabel30.setBounds(210, 30, 30, 20);

        jCheckBox23.setText("12. HBO HD   -       RS");
        jPanel10.add(jCheckBox23);
        jCheckBox23.setBounds(410, 20, 150, 30);

        jLabel31.setText("13.60");
        jPanel10.add(jLabel31);
        jLabel31.setBounds(600, 20, 30, 20);

        jCheckBox24.setText("13. MOVIES NOW HD   -       RS");
        jPanel10.add(jCheckBox24);
        jCheckBox24.setBounds(410, 60, 150, 30);

        jLabel77.setText("16.60");
        jPanel10.add(jLabel77);
        jLabel77.setBounds(600, 60, 30, 20);

        jCheckBox25.setText("14. MTV BEATS HD   -       RS");
        jPanel10.add(jCheckBox25);
        jCheckBox25.setBounds(410, 100, 150, 30);

        jLabel78.setText("2.60");
        jPanel10.add(jLabel78);
        jLabel78.setBounds(600, 100, 30, 20);

        jCheckBox26.setText("15. NG WILD HD   -       RS");
        jPanel10.add(jCheckBox26);
        jCheckBox26.setBounds(410, 140, 150, 30);

        jLabel79.setText("6.60");
        jPanel10.add(jLabel79);
        jLabel79.setBounds(600, 140, 30, 20);

        jCheckBox27.setText("17. STAR SPORTS HD   -       RS");
        jPanel10.add(jCheckBox27);
        jCheckBox27.setBounds(410, 230, 150, 20);

        jLabel81.setText("19.60");
        jPanel10.add(jLabel81);
        jLabel81.setBounds(600, 410, 30, 20);

        jLabel83.setText("19.00");
        jPanel10.add(jLabel83);
        jLabel83.setBounds(600, 230, 30, 20);

        jCheckBox28.setText("18. SAB TV HD   -       RS");
        jPanel10.add(jCheckBox28);
        jCheckBox28.setBounds(410, 260, 150, 30);

        jLabel84.setText("19.80");
        jPanel10.add(jLabel84);
        jLabel84.setBounds(600, 260, 30, 20);

        jCheckBox29.setText("19. SATMAX HD   -       RS");
        jPanel10.add(jCheckBox29);
        jCheckBox29.setBounds(410, 300, 150, 30);

        jLabel85.setText("18.60");
        jPanel10.add(jLabel85);
        jLabel85.setBounds(600, 300, 30, 20);

        jCheckBox30.setText("20. STAR GLOD HD   -       RS");
        jPanel10.add(jCheckBox30);
        jCheckBox30.setBounds(410, 340, 150, 23);

        jLabel86.setText("11.60");
        jPanel10.add(jLabel86);
        jLabel86.setBounds(600, 330, 30, 20);

        jCheckBox31.setText("21. STAR PLUS HD   -       RS");
        jPanel10.add(jCheckBox31);
        jCheckBox31.setBounds(410, 370, 150, 30);

        jLabel87.setText("19.60");
        jPanel10.add(jLabel87);
        jLabel87.setBounds(600, 370, 30, 20);

        jCheckBox32.setText("16. NICK HD   -       RS");
        jPanel10.add(jCheckBox32);
        jCheckBox32.setBounds(410, 180, 150, 30);

        jLabel88.setText("11.60");
        jPanel10.add(jLabel88);
        jLabel88.setBounds(600, 180, 30, 20);

        jCheckBox80.setText("6. COLORS INFINITY HD             RS");
        jPanel10.add(jCheckBox80);
        jCheckBox80.setBounds(10, 230, 160, 20);

        jLabel89.setText("10.60");
        jPanel10.add(jLabel89);
        jLabel89.setBounds(210, 230, 28, 10);

        jLabel90.setText("7.60");
        jPanel10.add(jLabel90);
        jLabel90.setBounds(210, 300, 22, 14);
        jPanel10.add(jTabbedPane4);
        jTabbedPane4.setBounds(100, -30, 5, 5);

        jButton6.setText("SUBMIT");
        jPanel10.add(jButton6);
        jButton6.setBounds(420, 450, 120, 40);

        jLabel91.setText("CHANNELS SELECTED  =");
        jPanel10.add(jLabel91);
        jLabel91.setBounds(40, 460, 130, 30);

        jLabel92.setText("NO");
        jPanel10.add(jLabel92);
        jLabel92.setBounds(180, 460, 60, 30);

        jLabel93.setText("PRICE(RS)         = ");
        jPanel10.add(jLabel93);
        jLabel93.setBounds(70, 490, 90, 30);

        jLabel94.setText("RS");
        jPanel10.add(jLabel94);
        jLabel94.setBounds(180, 490, 50, 20);

        jPanel3.add(jPanel10);
        jPanel10.setBounds(251, 52, 0, 0);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(7, 5, 660, 460);

        s1.setText("1.& FLIX   -       RS");
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        jPanel3.add(s1);
        s1.setBounds(10, 10, 150, 30);
        if(s1.isSelected()==true)
        {
            sdc.add(s1.getText());

            System.out.println(sdc.size());
            sdp.add(Integer.parseInt("15.80"));
        }

        jTabbedPane2.addTab("tab1", jPanel3);

        jPanel6.add(jTabbedPane2);
        jTabbedPane2.setBounds(20, 10, 680, 560);

        jTabbedPane1.addTab("A' LA CARTE", jPanel6);

        jPanel12.setLayout(null);

        starbt.setText("STAR BENGALI PACK");
        starbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starbtActionPerformed(evt);
            }
        });
        jPanel12.add(starbt);
        starbt.setBounds(40, 40, 180, 23);

        colorsbt.setText("COLORS PACK");
        colorsbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorsbtActionPerformed(evt);
            }
        });
        jPanel12.add(colorsbt);
        colorsbt.setBounds(40, 200, 180, 23);

        sonybt.setText("SONY HAPPY INDIA");
        sonybt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonybtActionPerformed(evt);
            }
        });
        jPanel12.add(sonybt);
        sonybt.setBounds(40, 350, 170, 23);

        star.setColumns(20);
        star.setRows(5);
        star.setText("\nChannel Details\nSr No \tChannel Name\n1\tSTAR PLUS\n2\tSTAR BHARAT\n3\tSTAR UTSAV\n4\tSTAR GOLD\n5\tMOVIES OK\n6\tSTAR UTSAV MOVIES\n7\tSTAR SPORTS 1 HINDI\n8\tSTAR SPORTS 2\n9\tSTAR SPORTS 3\n10\tSTAR SPORTS FIRST\n11\tNATIONAL GEOGRAPHIC\n12\tNAT GEO WILD\n");
        jScrollPane3.setViewportView(star);

        jPanel12.add(jScrollPane3);
        jScrollPane3.setBounds(350, 40, 360, 113);

        colors.setColumns(20);
        colors.setRows(5);
        colors.setText("\nChannel Details\nSr No \tChannel Name\n1\tCNBC AWAAZ\n2\tCOLORS\n3\tFYI TV 18\n4\tTHE HISTORY CHANNEL\n5\tMTV\n6\tMTV BEATS\n7\tNEWS18 BIHAR/JHARKHAND\n8\tNEWS18 INDIA\n9\tNEWS18 PUNJAB/HARYANA/HIMACHAL PRADESH\n10\tNEWS18 RAJASTHAN\n11\tNEWS18 UTTAR PRADESH/UTTARAKHAND\n12\tNEWS18 URDU\n13\tNew 18 North East\n14\tRISHTEY\n15\tRISHTEY CINEPLEX\n16\tNews 18 MP Chattisgarh\n17\tVH1\n18\tNICK\n19\tSONIC\n20\tNICK JUNIOR\n21\tCNN NEWS 18\n22\tCNBC TV 18\n");
        jScrollPane4.setViewportView(colors);

        jPanel12.add(jScrollPane4);
        jScrollPane4.setBounds(340, 190, 360, 100);

        sony.setColumns(20);
        sony.setRows(5);
        sony.setText("\nChannel Details\nSr No \tChannel Name\n1\tSET\n2\tSAB\n3\tPAL\n4\tSET MAX\n5\tMAX 2\n6\tSONY WAH\n7\tMIX\n8\tSONY YAY!\n9\tSONY AATH\n");
        jScrollPane5.setViewportView(sony);

        jPanel12.add(jScrollPane5);
        jScrollPane5.setBounds(340, 350, 360, 96);

        srb1.setText("Select");
        srb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srb1ActionPerformed(evt);
            }
        });
        jPanel12.add(srb1);
        srb1.setBounds(250, 40, 90, 23);
        if(srb1.isSelected()==true)
        {
            bs.setText(starbt.getText());
        }

        srb2.setText("Select");
        srb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srb2ActionPerformed(evt);
            }
        });
        jPanel12.add(srb2);
        srb2.setBounds(230, 200, 90, 23);

        srb3.setText("Select");
        jPanel12.add(srb3);
        srb3.setBounds(240, 350, 90, 23);
        if(srb3.isSelected()==true)
        {
            bs.setText(bs.getText()+","+sonybt.getText());
        }

        jLabel98.setText("jLabel98");
        jPanel12.add(jLabel98);
        jLabel98.setBounds(40, 80, 180, 20);

        jTabbedPane1.addTab(" Channel Bouquet", jPanel12);

        home.addTab("MAKE YOUR PACK", jTabbedPane1);

        getContentPane().add(home);
        home.setBounds(0, 0, 840, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sonybtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonybtActionPerformed
        // TODO add your handling code here:
        star.setVisible(false);
        colors.setVisible(false);
        sony.setVisible(true);
    }//GEN-LAST:event_sonybtActionPerformed

    private void colorsbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorsbtActionPerformed
        // TODO add your handling code here:
        sony.setVisible(false);
        star.setVisible(false);
        colors.setVisible(true);
    }//GEN-LAST:event_colorsbtActionPerformed

    private void starbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starbtActionPerformed
        sony.setVisible(false);
        colors.setVisible(false);
        star.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_starbtActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        example.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void srb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srb1ActionPerformed
        // TODO add your handling code here:
       
      bs.setText(bs.getText()+","+starbt.getText());
         System.out.println("working");
        
    }//GEN-LAST:event_srb1ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        // TODO add your handling code here:
        
        if(cb2.isSelected()==true)
        {
            cb1.setEnabled(false);
            pk.setText("SILVER");
            
        }
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your hanbdling code here:
         if(cb1.isSelected()==true)
        {
            cb2.setEnabled(false);
            pk.setText("BASIC");
            
        }
    }//GEN-LAST:event_cb1ActionPerformed

    private void srb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srb2ActionPerformed
        // TODO add your handling code here:
if(srb2.isSelected()==true)
{
    bs.setText(bs.getText()+","+colorsbt.getText());
    }//GEN-LAST:event_srb2ActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1ActionPerformed
    }
    /**set
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homea().setVisible(true);
                
   
           
            
            }
        });
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel amount;
    private javax.swing.JLabel bs;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    public javax.swing.JLabel ch;
    private javax.swing.JTextArea colors;
    private javax.swing.JButton colorsbt;
    private javax.swing.JTextArea example;
    public javax.swing.JTabbedPane home;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox80;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    public javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    public javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JLabel pk;
    private javax.swing.JCheckBox s1;
    private javax.swing.JTextArea sony;
    private javax.swing.JButton sonybt;
    private javax.swing.JRadioButton srb1;
    private javax.swing.JRadioButton srb2;
    private javax.swing.JRadioButton srb3;
    private javax.swing.JTextArea star;
    private javax.swing.JButton starbt;
    // End of variables declaration//GEN-END:variables
}

