/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VAIO
 */
public class home1 extends javax.swing.JFrame {

    /**
     * Creates new form home1
     */
    public home1() {
        initComponents();
       star.setVisible(false);
       sony.setVisible(false);
       colors.setVisible(false);
       
        setSize(500,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox33 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jCheckBox34 = new javax.swing.JCheckBox();
        jLabel32 = new javax.swing.JLabel();
        jCheckBox35 = new javax.swing.JCheckBox();
        jLabel33 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jCheckBox36 = new javax.swing.JCheckBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jCheckBox38 = new javax.swing.JCheckBox();
        jLabel36 = new javax.swing.JLabel();
        jCheckBox39 = new javax.swing.JCheckBox();
        jLabel37 = new javax.swing.JLabel();
        jCheckBox40 = new javax.swing.JCheckBox();
        jLabel38 = new javax.swing.JLabel();
        jCheckBox41 = new javax.swing.JCheckBox();
        jCheckBox42 = new javax.swing.JCheckBox();
        jCheckBox43 = new javax.swing.JCheckBox();
        jLabel39 = new javax.swing.JLabel();
        jCheckBox44 = new javax.swing.JCheckBox();
        jCheckBox45 = new javax.swing.JCheckBox();
        jLabel40 = new javax.swing.JLabel();
        jCheckBox46 = new javax.swing.JCheckBox();
        jLabel41 = new javax.swing.JLabel();
        jCheckBox47 = new javax.swing.JCheckBox();
        jLabel42 = new javax.swing.JLabel();
        jCheckBox48 = new javax.swing.JCheckBox();
        jLabel43 = new javax.swing.JLabel();
        jCheckBox49 = new javax.swing.JCheckBox();
        jLabel44 = new javax.swing.JLabel();
        jCheckBox50 = new javax.swing.JCheckBox();
        jLabel45 = new javax.swing.JLabel();
        jCheckBox51 = new javax.swing.JCheckBox();
        jLabel46 = new javax.swing.JLabel();
        jCheckBox52 = new javax.swing.JCheckBox();
        jLabel47 = new javax.swing.JLabel();
        jCheckBox53 = new javax.swing.JCheckBox();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jCheckBox54 = new javax.swing.JCheckBox();
        jLabel50 = new javax.swing.JLabel();
        jCheckBox55 = new javax.swing.JCheckBox();
        jLabel51 = new javax.swing.JLabel();
        jCheckBox56 = new javax.swing.JCheckBox();
        jLabel52 = new javax.swing.JLabel();
        jCheckBox57 = new javax.swing.JCheckBox();
        jLabel53 = new javax.swing.JLabel();
        jCheckBox58 = new javax.swing.JCheckBox();
        jLabel54 = new javax.swing.JLabel();
        jCheckBox59 = new javax.swing.JCheckBox();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jCheckBox60 = new javax.swing.JCheckBox();
        jLabel57 = new javax.swing.JLabel();
        jCheckBox61 = new javax.swing.JCheckBox();
        jLabel58 = new javax.swing.JLabel();
        jCheckBox62 = new javax.swing.JCheckBox();
        jLabel59 = new javax.swing.JLabel();
        jCheckBox63 = new javax.swing.JCheckBox();
        jLabel60 = new javax.swing.JLabel();
        jCheckBox64 = new javax.swing.JCheckBox();
        jLabel61 = new javax.swing.JLabel();
        jCheckBox65 = new javax.swing.JCheckBox();
        jLabel62 = new javax.swing.JLabel();
        jCheckBox66 = new javax.swing.JCheckBox();
        jLabel63 = new javax.swing.JLabel();
        jCheckBox67 = new javax.swing.JCheckBox();
        jLabel64 = new javax.swing.JLabel();
        jCheckBox68 = new javax.swing.JCheckBox();
        jLabel65 = new javax.swing.JLabel();
        jCheckBox69 = new javax.swing.JCheckBox();
        jLabel66 = new javax.swing.JLabel();
        jCheckBox70 = new javax.swing.JCheckBox();
        jLabel67 = new javax.swing.JLabel();
        jCheckBox71 = new javax.swing.JCheckBox();
        jLabel68 = new javax.swing.JLabel();
        jCheckBox72 = new javax.swing.JCheckBox();
        jLabel69 = new javax.swing.JLabel();
        jCheckBox73 = new javax.swing.JCheckBox();
        jLabel70 = new javax.swing.JLabel();
        jCheckBox74 = new javax.swing.JCheckBox();
        jLabel71 = new javax.swing.JLabel();
        jCheckBox75 = new javax.swing.JCheckBox();
        jLabel72 = new javax.swing.JLabel();
        jCheckBox76 = new javax.swing.JCheckBox();
        jLabel73 = new javax.swing.JLabel();
        jCheckBox77 = new javax.swing.JCheckBox();
        jLabel74 = new javax.swing.JLabel();
        jCheckBox78 = new javax.swing.JCheckBox();
        jLabel75 = new javax.swing.JLabel();
        jCheckBox79 = new javax.swing.JCheckBox();
        jLabel76 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox11 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox12 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox13 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jCheckBox19 = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jCheckBox20 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jCheckBox21 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jCheckBox22 = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jCheckBox23 = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        jCheckBox24 = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        jCheckBox25 = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        jCheckBox26 = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jCheckBox27 = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        jCheckBox28 = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        jCheckBox29 = new javax.swing.JCheckBox();
        jLabel27 = new javax.swing.JLabel();
        jCheckBox30 = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        jCheckBox31 = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        jCheckBox32 = new javax.swing.JCheckBox();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        star = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        colors = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        sony = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        jLabel1.setText("jLabel1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel3.setLayout(null);

        jPanel2.setLayout(null);

        jPanel6.setLayout(null);

        jCheckBox7.setText("22. ZEE TV HD   -       RS");
        jPanel6.add(jCheckBox7);
        jCheckBox7.setBounds(410, 410, 150, 30);

        jCheckBox8.setText("2. ANIMAL PLANET HD-  RS");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox8);
        jCheckBox8.setBounds(10, 70, 160, 20);

        jLabel4.setText("4.60");
        jPanel6.add(jLabel4);
        jLabel4.setBounds(210, 70, 30, 20);

        jCheckBox33.setText("11. FOX HD             RS");
        jPanel6.add(jCheckBox33);
        jCheckBox33.setBounds(10, 420, 160, 20);

        jLabel12.setText("2.60");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(210, 420, 22, 14);

        jCheckBox34.setText("3. BABY TV HD -               RS");
        jCheckBox34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox34ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox34);
        jCheckBox34.setBounds(10, 110, 160, 20);

        jLabel32.setText("2.60");
        jPanel6.add(jLabel32);
        jLabel32.setBounds(210, 110, 22, 14);

        jCheckBox35.setText("4.  AXN HD-                   RS");
        jPanel6.add(jCheckBox35);
        jCheckBox35.setBounds(10, 140, 160, 30);

        jLabel33.setText("5.80");
        jPanel6.add(jLabel33);
        jLabel33.setBounds(210, 150, 22, 14);

        jPanel7.setLayout(null);

        jCheckBox36.setText("1. AAJ TAK HD   -       RS");
        jPanel7.add(jCheckBox36);
        jCheckBox36.setBounds(10, 20, 150, 30);

        jCheckBox37.setText("2. ANIMAL PLANET-  RS");
        jCheckBox37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox37ActionPerformed(evt);
            }
        });
        jPanel7.add(jCheckBox37);
        jCheckBox37.setBounds(10, 70, 160, 20);

        jLabel34.setText("4.60");
        jPanel7.add(jLabel34);
        jLabel34.setBounds(210, 70, 30, 20);

        jLabel35.setText("3.60");
        jPanel7.add(jLabel35);
        jLabel35.setBounds(210, 30, 30, 20);

        jCheckBox38.setText("5. COLORS HD             RS");
        jPanel7.add(jCheckBox38);
        jCheckBox38.setBounds(10, 250, 160, 23);

        jLabel36.setText("9.60");
        jPanel7.add(jLabel36);
        jLabel36.setBounds(210, 200, 22, 14);

        jCheckBox39.setText("3. BABY TV-               RS");
        jPanel7.add(jCheckBox39);
        jCheckBox39.setBounds(10, 110, 160, 23);

        jLabel37.setText("2.60");
        jPanel7.add(jLabel37);
        jLabel37.setBounds(210, 110, 22, 14);

        jCheckBox40.setText("4.  AXN-                      RS");
        jPanel7.add(jCheckBox40);
        jCheckBox40.setBounds(10, 150, 160, 30);

        jLabel38.setText("5.80");
        jPanel7.add(jLabel38);
        jLabel38.setBounds(210, 150, 22, 14);

        jCheckBox41.setText("5. C N-                       RS");
        jPanel7.add(jCheckBox41);
        jCheckBox41.setBounds(10, 200, 160, 23);

        jCheckBox42.setText("5. C N-                       RS");
        jPanel7.add(jCheckBox42);
        jCheckBox42.setBounds(10, 200, 160, 23);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(0, 0, 0, 0);

        jCheckBox43.setText("5. COLORS HD             RS");
        jPanel6.add(jCheckBox43);
        jCheckBox43.setBounds(10, 190, 160, 23);

        jLabel39.setText("19.80");
        jPanel6.add(jLabel39);
        jLabel39.setBounds(210, 190, 28, 14);

        jCheckBox44.setText("7 . TUNER HD             RS");
        jPanel6.add(jCheckBox44);
        jCheckBox44.setBounds(10, 260, 160, 20);

        jCheckBox45.setText("9. LIVING FOOD  HD             RS");
        jPanel6.add(jCheckBox45);
        jCheckBox45.setBounds(10, 330, 160, 20);

        jLabel40.setText("11.60");
        jPanel6.add(jLabel40);
        jLabel40.setBounds(210, 330, 28, 14);

        jCheckBox46.setText("10. DISNEY HD             RS");
        jPanel6.add(jCheckBox46);
        jCheckBox46.setBounds(10, 380, 160, 20);

        jLabel41.setText("13.60");
        jPanel6.add(jLabel41);
        jLabel41.setBounds(210, 380, 28, 14);

        jCheckBox47.setText("8. DISCOVERY HD             RS");
        jPanel6.add(jCheckBox47);
        jCheckBox47.setBounds(10, 290, 160, 20);

        jLabel42.setText("3.20");
        jPanel6.add(jLabel42);
        jLabel42.setBounds(210, 260, 22, 14);

        jCheckBox48.setText("1. AAJ TAK HD   -       RS");
        jPanel6.add(jCheckBox48);
        jCheckBox48.setBounds(10, 20, 150, 30);

        jLabel43.setText("3.60");
        jPanel6.add(jLabel43);
        jLabel43.setBounds(210, 30, 30, 20);

        jCheckBox49.setText("12. HBO HD   -       RS");
        jPanel6.add(jCheckBox49);
        jCheckBox49.setBounds(410, 20, 150, 30);

        jLabel44.setText("13.60");
        jPanel6.add(jLabel44);
        jLabel44.setBounds(600, 20, 30, 20);

        jCheckBox50.setText("13. MOVIES NOW HD   -       RS");
        jPanel6.add(jCheckBox50);
        jCheckBox50.setBounds(410, 60, 150, 30);

        jLabel45.setText("16.60");
        jPanel6.add(jLabel45);
        jLabel45.setBounds(600, 60, 30, 20);

        jCheckBox51.setText("14. MTV BEATS HD   -       RS");
        jPanel6.add(jCheckBox51);
        jCheckBox51.setBounds(410, 100, 150, 30);

        jLabel46.setText("2.60");
        jPanel6.add(jLabel46);
        jLabel46.setBounds(600, 100, 30, 20);

        jCheckBox52.setText("15. NG WILD HD   -       RS");
        jPanel6.add(jCheckBox52);
        jCheckBox52.setBounds(410, 140, 150, 30);

        jLabel47.setText("6.60");
        jPanel6.add(jLabel47);
        jLabel47.setBounds(600, 140, 30, 20);

        jCheckBox53.setText("17. STAR SPORTS HD   -       RS");
        jPanel6.add(jCheckBox53);
        jCheckBox53.setBounds(410, 230, 150, 20);

        jLabel48.setText("19.60");
        jPanel6.add(jLabel48);
        jLabel48.setBounds(600, 410, 30, 20);

        jLabel49.setText("19.00");
        jPanel6.add(jLabel49);
        jLabel49.setBounds(600, 230, 30, 20);

        jCheckBox54.setText("18. SAB TV HD   -       RS");
        jPanel6.add(jCheckBox54);
        jCheckBox54.setBounds(410, 260, 150, 30);

        jLabel50.setText("19.80");
        jPanel6.add(jLabel50);
        jLabel50.setBounds(600, 260, 30, 20);

        jCheckBox55.setText("19. SATMAX HD   -       RS");
        jPanel6.add(jCheckBox55);
        jCheckBox55.setBounds(410, 300, 150, 30);

        jLabel51.setText("18.60");
        jPanel6.add(jLabel51);
        jLabel51.setBounds(600, 300, 30, 20);

        jCheckBox56.setText("20. STAR GLOD HD   -       RS");
        jPanel6.add(jCheckBox56);
        jCheckBox56.setBounds(410, 340, 150, 23);

        jLabel52.setText("11.60");
        jPanel6.add(jLabel52);
        jLabel52.setBounds(600, 330, 30, 20);

        jCheckBox57.setText("21. STAR PLUS HD   -       RS");
        jPanel6.add(jCheckBox57);
        jCheckBox57.setBounds(410, 370, 150, 30);

        jLabel53.setText("19.60");
        jPanel6.add(jLabel53);
        jLabel53.setBounds(600, 370, 30, 20);

        jCheckBox58.setText("16. NICK HD   -       RS");
        jPanel6.add(jCheckBox58);
        jCheckBox58.setBounds(410, 180, 150, 30);

        jLabel54.setText("11.60");
        jPanel6.add(jLabel54);
        jLabel54.setBounds(600, 180, 30, 20);

        jCheckBox59.setText("6. COLORS INFINITY HD             RS");
        jPanel6.add(jCheckBox59);
        jCheckBox59.setBounds(10, 230, 160, 20);

        jLabel55.setText("10.60");
        jPanel6.add(jLabel55);
        jLabel55.setBounds(210, 230, 28, 10);

        jLabel56.setText("7.60");
        jPanel6.add(jLabel56);
        jLabel56.setBounds(210, 300, 22, 14);
        jPanel6.add(jTabbedPane5);
        jTabbedPane5.setBounds(100, -30, 5, 5);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(263, 16, 0, 0);

        jCheckBox60.setText("10.BALLE BALLE       RS");
        jPanel2.add(jCheckBox60);
        jCheckBox60.setBounds(10, 370, 150, 30);

        jLabel57.setText("0.80");
        jPanel2.add(jLabel57);
        jLabel57.setBounds(200, 370, 30, 20);

        jCheckBox61.setText("12.BBC WORLD NEWS  -       RS");
        jPanel2.add(jCheckBox61);
        jCheckBox61.setBounds(400, 40, 150, 30);

        jLabel58.setText("0.80");
        jPanel2.add(jLabel58);
        jLabel58.setBounds(580, 370, 30, 20);

        jCheckBox62.setText("2.& PICTURES   -       RS");
        jPanel2.add(jCheckBox62);
        jCheckBox62.setBounds(10, 50, 150, 30);

        jLabel59.setText("6.80");
        jPanel2.add(jLabel59);
        jLabel59.setBounds(200, 50, 30, 20);

        jCheckBox63.setText("3.& TV -       RS");
        jPanel2.add(jCheckBox63);
        jCheckBox63.setBounds(10, 90, 150, 30);

        jLabel60.setText("12.80");
        jPanel2.add(jLabel60);
        jLabel60.setBounds(200, 90, 30, 20);

        jCheckBox64.setText("4.& 24 GHANTE -       RS");
        jPanel2.add(jCheckBox64);
        jCheckBox64.setBounds(10, 130, 150, 30);

        jLabel61.setText("1.30");
        jPanel2.add(jLabel61);
        jLabel61.setBounds(200, 130, 30, 20);

        jCheckBox65.setText("5.9X MUSIC -       RS");
        jPanel2.add(jCheckBox65);
        jCheckBox65.setBounds(10, 170, 150, 30);

        jLabel62.setText("0.80");
        jPanel2.add(jLabel62);
        jLabel62.setBounds(200, 170, 30, 20);

        jCheckBox66.setText("6.AAJ TAK -       RS");
        jPanel2.add(jCheckBox66);
        jCheckBox66.setBounds(10, 210, 150, 30);

        jLabel63.setText("1.80");
        jPanel2.add(jLabel63);
        jLabel63.setBounds(200, 210, 30, 20);

        jCheckBox67.setText("7. ABP NEWS       RS");
        jPanel2.add(jCheckBox67);
        jCheckBox67.setBounds(10, 250, 150, 30);

        jLabel64.setText("0.80");
        jPanel2.add(jLabel64);
        jLabel64.setBounds(200, 250, 30, 20);

        jCheckBox68.setText("8. ASIANET MOVIES      RS");
        jPanel2.add(jCheckBox68);
        jCheckBox68.setBounds(10, 290, 150, 30);

        jLabel65.setText("15.80");
        jPanel2.add(jLabel65);
        jLabel65.setBounds(200, 290, 30, 20);

        jCheckBox69.setText("9.AXN       RS");
        jPanel2.add(jCheckBox69);
        jCheckBox69.setBounds(10, 330, 150, 30);

        jLabel66.setText("5.80");
        jPanel2.add(jLabel66);
        jLabel66.setBounds(200, 330, 30, 20);

        jCheckBox70.setText("1.& FLIX   -       RS");
        jPanel2.add(jCheckBox70);
        jCheckBox70.setBounds(10, 10, 150, 30);

        jLabel67.setText("15.80");
        jPanel2.add(jLabel67);
        jLabel67.setBounds(200, 20, 30, 20);

        jCheckBox71.setText("20.9X TASHAN       RS");
        jPanel2.add(jCheckBox71);
        jCheckBox71.setBounds(400, 370, 150, 30);

        jLabel68.setText("4.80");
        jPanel2.add(jLabel68);
        jLabel68.setBounds(580, 20, 30, 20);

        jCheckBox72.setText("11.BBC EARTH   -       RS");
        jPanel2.add(jCheckBox72);
        jCheckBox72.setBounds(400, 10, 150, 30);

        jLabel69.setText("1.80");
        jPanel2.add(jLabel69);
        jLabel69.setBounds(580, 40, 30, 20);

        jCheckBox73.setText("13.BINDASS  -       RS");
        jPanel2.add(jCheckBox73);
        jCheckBox73.setBounds(400, 80, 150, 30);

        jLabel70.setText("1.80");
        jPanel2.add(jLabel70);
        jLabel70.setBounds(580, 80, 30, 20);

        jCheckBox74.setText("14.CARE WORLD  -       RS");
        jPanel2.add(jCheckBox74);
        jCheckBox74.setBounds(400, 120, 150, 30);

        jLabel71.setText("0.80");
        jPanel2.add(jLabel71);
        jLabel71.setBounds(580, 120, 30, 20);

        jCheckBox75.setText("15.BIO SCIENCE  -       RS");
        jPanel2.add(jCheckBox75);
        jCheckBox75.setBounds(400, 160, 150, 30);

        jLabel72.setText("0.80");
        jPanel2.add(jLabel72);
        jLabel72.setBounds(580, 160, 30, 20);

        jCheckBox76.setText("16.CNBC TV18  -       RS");
        jPanel2.add(jCheckBox76);
        jCheckBox76.setBounds(400, 200, 150, 30);

        jLabel73.setText("2.80");
        jPanel2.add(jLabel73);
        jLabel73.setBounds(580, 200, 30, 20);

        jCheckBox77.setText("17.CNN NEWS  -       RS");
        jPanel2.add(jCheckBox77);
        jCheckBox77.setBounds(400, 250, 150, 30);

        jLabel74.setText("2.80");
        jPanel2.add(jLabel74);
        jLabel74.setBounds(580, 250, 30, 20);

        jCheckBox78.setText("18.COLORS  -       RS");
        jPanel2.add(jCheckBox78);
        jCheckBox78.setBounds(400, 290, 150, 30);

        jLabel75.setText("19.80");
        jPanel2.add(jLabel75);
        jLabel75.setBounds(580, 290, 30, 20);

        jCheckBox79.setText("19.D SPORTS  -       RS");
        jPanel2.add(jCheckBox79);
        jCheckBox79.setBounds(400, 330, 150, 30);

        jLabel76.setText("4.80");
        jPanel2.add(jLabel76);
        jLabel76.setBounds(580, 330, 30, 20);

        jLabel80.setText("CHANNELS SELECTED  =");
        jPanel2.add(jLabel80);
        jLabel80.setBounds(30, 430, 130, 30);

        jLabel81.setText("NO");
        jPanel2.add(jLabel81);
        jLabel81.setBounds(160, 430, 60, 30);

        jLabel82.setText("PRICE(RS)         = ");
        jPanel2.add(jLabel82);
        jLabel82.setBounds(60, 470, 90, 30);

        jLabel83.setText("RS");
        jPanel2.add(jLabel83);
        jLabel83.setBounds(160, 480, 50, 20);

        jButton5.setText("SUBMIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(400, 440, 120, 40);

        jTabbedPane2.addTab("Standard definition(SD)", jPanel2);

        jPanel4.setLayout(null);

        jCheckBox2.setText("22. ZEE TV HD   -       RS");
        jPanel4.add(jCheckBox2);
        jCheckBox2.setBounds(410, 410, 150, 30);

        jCheckBox3.setText("2. ANIMAL PLANET HD-  RS");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox3);
        jCheckBox3.setBounds(10, 70, 160, 20);

        jLabel3.setText("4.60");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(210, 70, 30, 20);

        jCheckBox4.setText("11. FOX HD             RS");
        jPanel4.add(jCheckBox4);
        jCheckBox4.setBounds(10, 420, 160, 20);

        jLabel2.setText("2.60");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(210, 420, 22, 14);

        jCheckBox5.setText("3. BABY TV HD -               RS");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox5);
        jCheckBox5.setBounds(10, 110, 160, 20);

        jLabel5.setText("2.60");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(210, 110, 22, 14);

        jCheckBox6.setText("4.  AXN HD-                   RS");
        jPanel4.add(jCheckBox6);
        jCheckBox6.setBounds(10, 140, 160, 30);

        jLabel6.setText("5.80");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(210, 150, 22, 14);

        jPanel5.setLayout(null);

        jCheckBox9.setText("1. AAJ TAK HD   -       RS");
        jPanel5.add(jCheckBox9);
        jCheckBox9.setBounds(10, 20, 150, 30);

        jCheckBox10.setText("2. ANIMAL PLANET-  RS");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox10);
        jCheckBox10.setBounds(10, 70, 160, 20);

        jLabel7.setText("4.60");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(210, 70, 30, 20);

        jLabel8.setText("3.60");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(210, 30, 30, 20);

        jCheckBox11.setText("5. COLORS HD             RS");
        jPanel5.add(jCheckBox11);
        jCheckBox11.setBounds(10, 250, 160, 23);

        jLabel9.setText("9.60");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(210, 200, 22, 14);

        jCheckBox12.setText("3. BABY TV-               RS");
        jPanel5.add(jCheckBox12);
        jCheckBox12.setBounds(10, 110, 160, 23);

        jLabel10.setText("2.60");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(210, 110, 22, 14);

        jCheckBox13.setText("4.  AXN-                      RS");
        jPanel5.add(jCheckBox13);
        jCheckBox13.setBounds(10, 150, 160, 30);

        jLabel11.setText("5.80");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(210, 150, 22, 14);

        jCheckBox14.setText("5. C N-                       RS");
        jPanel5.add(jCheckBox14);
        jCheckBox14.setBounds(10, 200, 160, 23);

        jCheckBox15.setText("5. C N-                       RS");
        jPanel5.add(jCheckBox15);
        jCheckBox15.setBounds(10, 200, 160, 23);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(0, 0, 0, 0);

        jCheckBox16.setText("5. COLORS HD             RS");
        jPanel4.add(jCheckBox16);
        jCheckBox16.setBounds(10, 190, 160, 23);

        jLabel13.setText("19.80");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(210, 190, 28, 14);

        jCheckBox17.setText("7 . TUNER HD             RS");
        jPanel4.add(jCheckBox17);
        jCheckBox17.setBounds(10, 260, 160, 20);

        jCheckBox18.setText("9. LIVING FOOD  HD             RS");
        jPanel4.add(jCheckBox18);
        jCheckBox18.setBounds(10, 330, 160, 20);

        jLabel15.setText("11.60");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(210, 330, 28, 14);

        jCheckBox19.setText("10. DISNEY HD             RS");
        jPanel4.add(jCheckBox19);
        jCheckBox19.setBounds(10, 380, 160, 20);

        jLabel16.setText("13.60");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(210, 380, 28, 14);

        jCheckBox20.setText("8. DISCOVERY HD             RS");
        jPanel4.add(jCheckBox20);
        jCheckBox20.setBounds(10, 290, 160, 20);

        jLabel17.setText("3.20");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(210, 260, 22, 14);

        jCheckBox21.setText("1. AAJ TAK HD   -       RS");
        jPanel4.add(jCheckBox21);
        jCheckBox21.setBounds(10, 30, 150, 30);

        jLabel18.setText("3.60");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(210, 30, 30, 20);

        jCheckBox22.setText("12. HBO HD   -       RS");
        jPanel4.add(jCheckBox22);
        jCheckBox22.setBounds(410, 20, 150, 30);

        jLabel19.setText("13.60");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(600, 20, 30, 20);

        jCheckBox23.setText("13. MOVIES NOW HD   -       RS");
        jPanel4.add(jCheckBox23);
        jCheckBox23.setBounds(410, 60, 150, 30);

        jLabel20.setText("16.60");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(600, 60, 30, 20);

        jCheckBox24.setText("14. MTV BEATS HD   -       RS");
        jPanel4.add(jCheckBox24);
        jCheckBox24.setBounds(410, 100, 150, 30);

        jLabel21.setText("2.60");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(600, 100, 30, 20);

        jCheckBox25.setText("15. NG WILD HD   -       RS");
        jPanel4.add(jCheckBox25);
        jCheckBox25.setBounds(410, 140, 150, 30);

        jLabel22.setText("6.60");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(600, 140, 30, 20);

        jCheckBox26.setText("17. STAR SPORTS HD   -       RS");
        jPanel4.add(jCheckBox26);
        jCheckBox26.setBounds(410, 230, 150, 20);

        jLabel23.setText("19.60");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(600, 410, 30, 20);

        jLabel24.setText("19.00");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(600, 230, 30, 20);

        jCheckBox27.setText("18. SAB TV HD   -       RS");
        jPanel4.add(jCheckBox27);
        jCheckBox27.setBounds(410, 260, 150, 30);

        jLabel25.setText("19.80");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(600, 260, 30, 20);

        jCheckBox28.setText("19. SATMAX HD   -       RS");
        jPanel4.add(jCheckBox28);
        jCheckBox28.setBounds(410, 300, 150, 30);

        jLabel26.setText("18.60");
        jPanel4.add(jLabel26);
        jLabel26.setBounds(600, 300, 30, 20);

        jCheckBox29.setText("20. STAR GLOD HD   -       RS");
        jPanel4.add(jCheckBox29);
        jCheckBox29.setBounds(410, 340, 150, 23);

        jLabel27.setText("11.60");
        jPanel4.add(jLabel27);
        jLabel27.setBounds(600, 330, 30, 20);

        jCheckBox30.setText("21. STAR PLUS HD   -       RS");
        jPanel4.add(jCheckBox30);
        jCheckBox30.setBounds(410, 370, 150, 30);

        jLabel28.setText("19.60");
        jPanel4.add(jLabel28);
        jLabel28.setBounds(600, 370, 30, 20);

        jCheckBox31.setText("16. NICK HD   -       RS");
        jPanel4.add(jCheckBox31);
        jCheckBox31.setBounds(410, 180, 150, 30);

        jLabel29.setText("11.60");
        jPanel4.add(jLabel29);
        jLabel29.setBounds(600, 180, 30, 20);

        jCheckBox32.setText("6. COLORS INFINITY HD             RS");
        jPanel4.add(jCheckBox32);
        jCheckBox32.setBounds(10, 230, 160, 20);

        jLabel30.setText("10.60");
        jPanel4.add(jLabel30);
        jLabel30.setBounds(210, 230, 28, 10);

        jLabel31.setText("7.60");
        jPanel4.add(jLabel31);
        jLabel31.setBounds(210, 300, 22, 14);
        jPanel4.add(jTabbedPane4);
        jTabbedPane4.setBounds(100, -30, 5, 5);

        jButton4.setText("SUBMIT");
        jPanel4.add(jButton4);
        jButton4.setBounds(410, 470, 120, 40);

        jLabel14.setText("CHANNELS SELECTED  =");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(40, 460, 130, 30);

        jLabel77.setText("NO");
        jPanel4.add(jLabel77);
        jLabel77.setBounds(180, 460, 60, 30);

        jLabel78.setText("PRICE(RS)         = ");
        jPanel4.add(jLabel78);
        jLabel78.setBounds(70, 490, 90, 30);

        jLabel79.setText("RS");
        jPanel4.add(jLabel79);
        jLabel79.setBounds(180, 490, 50, 20);

        jTabbedPane2.addTab("High Definition(HD)", jPanel4);

        jPanel3.add(jTabbedPane2);
        jTabbedPane2.setBounds(20, 10, 680, 560);

        jTabbedPane1.addTab("A' LA CARTE", jPanel3);

        jPanel1.setLayout(null);

        jButton1.setText("STAR BENGALI PACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 70, 180, 23);

        jButton2.setText("COLORS PACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(40, 230, 180, 23);

        jButton3.setText("SONY HAPPY INDIA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(40, 370, 170, 23);

        star.setColumns(20);
        star.setRows(5);
        star.setText("\nChannel Details\nSr No \tChannel Name\n1\tSTAR PLUS\n2\tSTAR BHARAT\n3\tSTAR UTSAV\n4\tSTAR GOLD\n5\tMOVIES OK\n6\tSTAR UTSAV MOVIES\n7\tSTAR SPORTS 1 HINDI\n8\tSTAR SPORTS 2\n9\tSTAR SPORTS 3\n10\tSTAR SPORTS FIRST\n11\tNATIONAL GEOGRAPHIC\n12\tNAT GEO WILD\n");
        jScrollPane1.setViewportView(star);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(350, 40, 360, 113);

        colors.setColumns(20);
        colors.setRows(5);
        colors.setText("\nChannel Details\nSr No \tChannel Name\n1\tCNBC AWAAZ\n2\tCOLORS\n3\tFYI TV 18\n4\tTHE HISTORY CHANNEL\n5\tMTV\n6\tMTV BEATS\n7\tNEWS18 BIHAR/JHARKHAND\n8\tNEWS18 INDIA\n9\tNEWS18 PUNJAB/HARYANA/HIMACHAL PRADESH\n10\tNEWS18 RAJASTHAN\n11\tNEWS18 UTTAR PRADESH/UTTARAKHAND\n12\tNEWS18 URDU\n13\tNew 18 North East\n14\tRISHTEY\n15\tRISHTEY CINEPLEX\n16\tNews 18 MP Chattisgarh\n17\tVH1\n18\tNICK\n19\tSONIC\n20\tNICK JUNIOR\n21\tCNN NEWS 18\n22\tCNBC TV 18\n");
        jScrollPane2.setViewportView(colors);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(340, 190, 360, 100);

        sony.setColumns(20);
        sony.setRows(5);
        sony.setText("\nChannel Details\nSr No \tChannel Name\n1\tSET\n2\tSAB\n3\tPAL\n4\tSET MAX\n5\tMAX 2\n6\tSONY WAH\n7\tMIX\n8\tSONY YAY!\n9\tSONY AATH\n");
        jScrollPane3.setViewportView(sony);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(340, 350, 360, 96);

        jRadioButton1.setText("Select");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(240, 70, 90, 23);

        jRadioButton2.setText("Select");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(240, 230, 90, 23);

        jRadioButton3.setText("Select");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(240, 370, 90, 23);

        jTabbedPane1.addTab(" Channel Bouquet", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 720, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox37ActionPerformed

    private void jCheckBox34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox34ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 sony.setVisible(false);
 colors.setVisible(false);
        star.setVisible(true);
       
               // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        sony.setVisible(false);
        star.setVisible(false);
        colors.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        star.setVisible(false);
        colors.setVisible(false);
        sony.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
dispose();        // TODO add your handling code here:
    
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea colors;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox37;
    private javax.swing.JCheckBox jCheckBox38;
    private javax.swing.JCheckBox jCheckBox39;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox40;
    private javax.swing.JCheckBox jCheckBox41;
    private javax.swing.JCheckBox jCheckBox42;
    private javax.swing.JCheckBox jCheckBox43;
    private javax.swing.JCheckBox jCheckBox44;
    private javax.swing.JCheckBox jCheckBox45;
    private javax.swing.JCheckBox jCheckBox46;
    private javax.swing.JCheckBox jCheckBox47;
    private javax.swing.JCheckBox jCheckBox48;
    private javax.swing.JCheckBox jCheckBox49;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox50;
    private javax.swing.JCheckBox jCheckBox51;
    private javax.swing.JCheckBox jCheckBox52;
    private javax.swing.JCheckBox jCheckBox53;
    private javax.swing.JCheckBox jCheckBox54;
    private javax.swing.JCheckBox jCheckBox55;
    private javax.swing.JCheckBox jCheckBox56;
    private javax.swing.JCheckBox jCheckBox57;
    private javax.swing.JCheckBox jCheckBox58;
    private javax.swing.JCheckBox jCheckBox59;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox60;
    private javax.swing.JCheckBox jCheckBox61;
    private javax.swing.JCheckBox jCheckBox62;
    private javax.swing.JCheckBox jCheckBox63;
    private javax.swing.JCheckBox jCheckBox64;
    private javax.swing.JCheckBox jCheckBox65;
    private javax.swing.JCheckBox jCheckBox66;
    private javax.swing.JCheckBox jCheckBox67;
    private javax.swing.JCheckBox jCheckBox68;
    private javax.swing.JCheckBox jCheckBox69;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox70;
    private javax.swing.JCheckBox jCheckBox71;
    private javax.swing.JCheckBox jCheckBox72;
    private javax.swing.JCheckBox jCheckBox73;
    private javax.swing.JCheckBox jCheckBox74;
    private javax.swing.JCheckBox jCheckBox75;
    private javax.swing.JCheckBox jCheckBox76;
    private javax.swing.JCheckBox jCheckBox77;
    private javax.swing.JCheckBox jCheckBox78;
    private javax.swing.JCheckBox jCheckBox79;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextArea sony;
    private javax.swing.JTextArea star;
    // End of variables declaration//GEN-END:variables
}
